require('./authentication-verifier.test')
require('./hooks/check-password.test')
require('./hooks/check-email-code.test')
require('./hooks/create-email-code.test')
require('./hooks/create-temp-password.test')
require('./services/users.hook.patch.test')
