require('./authentication-verifier.test')
require('./hooks/check-password.test')
require('./hooks/check-email-code.test')
require('./hooks/create-email-code.test')
require('./hooks/create-tmp-password.test')
require('./hooks/users.hook.patch.test')
require('./hooks/blog.add-link-title.test')

require('./services/blog.test')
// require('./services/faq.test')
// require('./services/profile.test')
// require('./services/shop.test')
// require('./services/uploads.test')
// require('./services/users.test')
